name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build_macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: build examples
      run: make examples
    - name: run test
      run: ./hammer_test
      
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build examples
      run: make examples
    - name: run test
      run: ./hammer_test
